manipulator:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_tpye: Distance
  kinematics_solver_search_resolution: 0.0005
  kinematics_solver_timeout: 0.01
  # kinematics_solver: bio_ik/BioIKKinematicsPlugin
  # kinematics_solver_search_resolution: 0.005
  # kinematics_solver_timeout: 0.05
  # max_iterations: 100
  # mode: gd_c
  
